/**
 * Shared uptime-check utilities — imported by both `scripts/uptime-check.mjs`
 * (via dynamic import or re-export) and `scripts/uptime-check.test.ts`.
 *
 * Kept minimal: only the functions that need direct unit-test coverage live
 * here.  The orchestration logic (STATE, renderStatusMd, main) stays in the
 * .mjs script so the CLI remains zero-dependency.
 */

/** Default API base used by the uptime check. */
export const DEFAULT_API_URL = "https://quay-api.onrender.com";

/**
 * Synthetic create-link check.
 *
 * 1. POST /links with bearer auth (apiKey) — proves the public write path works.
 * 2. Assert 201.
 * 3. Cancel the created link via POST /links/:id/cancel so synthetic rows
 *    don't accumulate in the database.
 */
export async function checkSyntheticLink(
  apiUrl: string,
  apiKey: string | null,
  fetchFn: typeof globalThis.fetch = globalThis.fetch,
): Promise<void> {
  const headers: Record<string, string> = { "content-type": "application/json" };
  if (apiKey) {
    headers.authorization = `Bearer ${apiKey}`;
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 15_000);

  let createRes: Response;
  try {
    createRes = await fetchFn(`${apiUrl}/links`, {
      method: "POST",
      headers,
      body: JSON.stringify({ title: "uptime-check", amount: "0.0000001", assetCode: "XLM" }),
      signal: controller.signal,
    });
  } finally {
    clearTimeout(timer);
  }

  if (createRes.status === 401 && !apiKey) {
    throw new Error(
      "POST /links -> HTTP 401 and UPTIME_API_KEY is not set. " +
        "Add a least-privilege API key (links:read + links:write) as the UPTIME_API_KEY repo secret.",
    );
  }

  if (createRes.status !== 201) {
    throw new Error(`POST ${apiUrl}/links -> HTTP ${createRes.status} (expected 201)`);
  }

  // --- Best-effort cleanup: cancel the throwaway link. --------------------
  try {
    const body = (await createRes.json()) as { link?: { id?: string } };
    const linkId = body?.link?.id;
    if (linkId) {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 15_000);
      try {
        const cancelRes = await fetchFn(`${apiUrl}/links/${linkId}/cancel`, {
          method: "POST",
          headers,
          signal: ctrl.signal,
        });
        if (!cancelRes.ok) {
          console.warn(
            `[uptime] warning: failed to cancel synthetic link ${linkId} (HTTP ${cancelRes.status})`,
          );
        }
      } finally {
        clearTimeout(t);
      }
    }
  } catch {
    // Best-effort — ignore cleanup errors.
  }
}

/** GET a URL and throw on non-OK. */
export async function checkGet(
  url: string,
  fetchFn: typeof globalThis.fetch = globalThis.fetch,
): Promise<void> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 15_000);
  try {
    const res = await fetchFn(url, { method: "GET", signal: controller.signal });
    if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Render the STATUS.md content.  The `lastRegenerated` parameter is injected
 * so tests can assert on it without mocking Date.
 */
export function renderStatusMdContent(state: Record<string, unknown>, lastRegenerated: string): string {
  const lines = [
    "# Status",
    "",
    `> **Last regenerated:** ${lastRegenerated}`,
    "",
    "Generated by `.github/workflows/uptime.yml` (every 5 minutes) — do not edit by hand.",
    "",
  ];
  // The full rendering logic lives in the .mjs script; here we just produce
  // the header + any target sections that exist in the state.
  const targets = (state as { targets?: Record<string, unknown> }).targets ?? {};
  for (const [id, t] of Object.entries(targets)) {
    const target = t as {
      lastStatus?: string;
      lastCheckedAt?: string;
      consecutiveFailures?: number;
      lastError?: string | null;
      history?: Array<{ date: string; up: number; down: number }>;
      today?: { date: string; up: number; down: number } | null;
    };
    lines.push(`## ${id}`);
    lines.push("");
    lines.push(
      `- Status: **${target.lastStatus === "up" ? "🟢 up" : "🔴 down"}** (last checked ${target.lastCheckedAt})`,
    );
    if (target.lastError) lines.push(`- Last error: \`${target.lastError}\``);
    lines.push("");
  }
  return lines.join("\n");
}
